export const getApiDocs = (req, res) => {
  return res.json({
    success: true,
    message: 'HRMS API documentation',
    data: {
      endpoints: [
        { path: '/api/auth/register', method: 'POST', description: 'Register a new user' },
        { path: '/api/auth/login', method: 'POST', description: 'Login user' },
        { path: '/api/auth/me', method: 'GET', description: 'Get current authenticated user' },
        { path: '/api/employees', method: 'GET', description: 'Get all employees' },
        { path: '/api/employees/:id', method: 'GET', description: 'Get employee by id' },
        { path: '/api/employees', method: 'POST', description: 'Create a new employee' },
        { path: '/api/employees/:id', method: 'PUT', description: 'Update employee' },
        { path: '/api/employees/:id', method: 'DELETE', description: 'Delete employee' },
        { path: '/api/departments', method: 'GET', description: 'Get all departments' },
        { path: '/api/departments/:id', method: 'GET', description: 'Get department by id' },
        { path: '/api/departments', method: 'POST', description: 'Create department' },
        { path: '/api/departments/:id', method: 'PUT', description: 'Update department' },
        { path: '/api/departments/:id', method: 'DELETE', description: 'Delete department' },
        { path: '/api/attendance/checkin', method: 'POST', description: 'Mark attendance check-in' },
        { path: '/api/attendance/checkout', method: 'POST', description: 'Mark attendance check-out' },
        { path: '/api/attendance/me', method: 'GET', description: 'Get authenticated employee attendance' },
        { path: '/api/attendance', method: 'GET', description: 'Get all attendance records' },
        { path: '/api/attendance/employee/:id', method: 'GET', description: 'Get attendance for employee' },
        { path: '/api/leaves', method: 'POST', description: 'Apply for leave' },
        { path: '/api/leaves/me', method: 'GET', description: 'Get my leaves' },
        { path: '/api/leaves', method: 'GET', description: 'Get all leaves' },
        { path: '/api/leaves/:id', method: 'GET', description: 'Get leave by id' },
        { path: '/api/leaves/:id/approve', method: 'PUT', description: 'Approve leave' },
        { path: '/api/leaves/:id/reject', method: 'PUT', description: 'Reject leave' },
        { path: '/api/leaves/:id/cancel', method: 'PUT', description: 'Cancel leave' },
        { path: '/api/leaves/:id', method: 'DELETE', description: 'Delete leave' },
        { path: '/api/payroll', method: 'POST', description: 'Generate payroll' },
        { path: '/api/payroll/me', method: 'GET', description: 'Get payroll for current user' },
        { path: '/api/payroll', method: 'GET', description: 'Get all payroll records' },
        { path: '/api/payroll/:id', method: 'GET', description: 'Get payroll by id' },
        { path: '/api/payroll/:id', method: 'PUT', description: 'Update payroll' },
        { path: '/api/payroll/:id/pay', method: 'PUT', description: 'Mark payroll as paid' },
        { path: '/api/payroll/:id', method: 'DELETE', description: 'Delete payroll' },
        { path: '/api/dashboard/stats', method: 'GET', description: 'Get dashboard stats' },
        { path: '/api/upload/profile', method: 'POST', description: 'Upload profile picture' },
        { path: '/api/upload/document', method: 'POST', description: 'Upload document or resume' },
      ],
    },
  });
};
